base_url = "https://daniilmira.com"
compile_sass = true
title = "Daniil Mira: Resume"
description = "Resume"
generate_feed = false
build_search_index = false
taxonomies = [{ name = "tags", feed = false }]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Daniil"
last_name = "Mira"
address = "Rheinberg, Germany"
email = "contact@daniilmira.com"
github = "https://github.com/ZAZPRO/"
favicon = "/favicon.ico"
avatar = "/media/avatar.jpg"

katex = false
show_about = false
show_skills = true
show_projects = false
show_opensource = false
show_publications = false
show_experience = true
show_education = true
show_blog = false
